---
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  name: kubevirt-actuator-testing-machine8
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: kubevirt
spec:
  metadata:
    labels:
      node-role.kubernetes.io/master: ""
      node-role.kubernetes.io/infra: ""
  providerSpec:
    value:
      # TODO: determine the version : apiVersion: kubevirtproviderconfig.openshift.io/v1beta1
      kind: KubevirtMachineProviderSpec
      SecretName: underkube-config
      SourcePvcName: pvc-rhcos-image
