apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: >-
      https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.4/44.81.202003062006-0/x86_64/rhcos-44.81.202003062006-0-qemu.x86_64.qcow2.gz
  name: pvc-rhcos-image
  namespace: openshift-machine-api
spec:
  #storageClassName: trident
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
#    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
